# Generated by Django 6.1 on 2026-10-07 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('dark', 'Dark Theme'), ('gray', 'Gray Theme'), ('light', 'Light Theme')], default='dark', max_length=10)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=10)),
                ('ritual_reminders', models.BooleanField(default=False)),
                ('task_reminders', models.BooleanField(default=False)),
                ('alignment_reminders', models.BooleanField(default=False)),
                ('reminder_time', models.CharField(choices=[('06:00', '6:00 AM'), ('07:00', '7:00 AM'), ('08:00', '8:00 AM'), ('09:00', '9:00 AM'), ('10:00', '10:00 AM'), ('11:00', '11:00 AM'), ('12:00', '12:00 PM'), ('13:00', '1:00 PM'), ('14:00', '2:00 PM'), ('15:00', '3:00 PM'), ('16:00', '4:00 PM'), ('17:00', '5:00 PM'), ('18:00', '6:00 PM'), ('19:00', '7:00 PM'), ('20:00', '8:00 PM'), ('21:00', '9:00 PM'), ('22:00', '10:00 PM')], default='08:00', max_length=5)),
                ('dashboard_layout', models.CharField(choices=[('compact', 'Compact'), ('standard', 'Standard'), ('expanded', 'Expanded')], default='standard', max_length=10)),
                ('four_forces_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
