# Generated by Django 6.1 on 2026-09-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_healing_path', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healinglog',
            name='belief',
            field=models.CharField(blank=True, help_text='Associated belief or affirmation', max_length=255),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='intensity',
            field=models.PositiveSmallIntegerField(default=5, help_text='Intensity 1-10'),
        ),
        migrations.AlterField(
            model_name='healinglog',
            name='stage',
            field=models.CharField(choices=[('tension_observer', 'Tension Observer'), ('awareness_lens', 'Awareness Lens'), ('belief_anchor', 'Belief Anchor'), ('thought_analyzer', 'Thought Analyzer'), ('faith_cycle', 'Faith Cycle'), ('clarity_flow', 'Clarity Flow'), ('confidence_tracker', 'Confidence Tracker'), ('celebration', 'Celebration')], max_length=50),
        ),
    ]
