# Generated by Django 6.1 on 2026-09-06 09:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_healing_path', '0002_healinglog_belief_healinglog_intensity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransformationJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('tension_observer', 'Tension Observer'), ('awareness_lens', 'Awareness Lens'), ('belief_anchor', 'Belief Anchor'), ('thought_analyzer', 'Thought Analyzer'), ('faith_cycle', 'Faith Cycle'), ('clarity_flow', 'Clarity Flow'), ('confidence_tracker', 'Confidence Tracker'), ('celebration', 'Celebration')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tension_log', models.ForeignKey(help_text='The original tension that started this journey', on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='Core_healing_path.healinglog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformation_journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='JourneyStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('tension_observer', 'Tension Observer'), ('awareness_lens', 'Awareness Lens'), ('belief_anchor', 'Belief Anchor'), ('thought_analyzer', 'Thought Analyzer'), ('faith_cycle', 'Faith Cycle'), ('clarity_flow', 'Clarity Flow'), ('confidence_tracker', 'Confidence Tracker'), ('celebration', 'Celebration')], max_length=50)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_stages', to='Core_healing_path.healinglog')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='Core_healing_path.transformationjourney')),
            ],
            options={
                'ordering': ['completed_at'],
            },
        ),
    ]
