# Generated by Django 6.1 on 2026-09-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_healing_path', '0003_transformationjourney_journeystage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healinglog',
            name='belief',
        ),
        migrations.AddField(
            model_name='healinglog',
            name='celebration_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='clarity_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='coping_strategy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='custom_affirmation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='emotion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='gratitude_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='insight_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='joy_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='limiting_belief',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='reframe',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='ritual',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='trigger',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='healinglog',
            name='intensity',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='healinglog',
            name='stage',
            field=models.CharField(choices=[('tension_observer', 'Tension Observer'), ('awareness_lens', 'Awareness Lens'), ('belief_anchor', 'Belief Anchor'), ('thought_analyzer', 'Thought Analyzer'), ('faith_cycle', 'Faith Cycle'), ('clarity_flow', 'Clarity Flow'), ('celebration', 'Celebration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='journeystage',
            name='stage',
            field=models.CharField(choices=[('tension_observer', 'Tension Observer'), ('awareness_lens', 'Awareness Lens'), ('belief_anchor', 'Belief Anchor'), ('thought_analyzer', 'Thought Analyzer'), ('faith_cycle', 'Faith Cycle'), ('clarity_flow', 'Clarity Flow'), ('celebration', 'Celebration')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transformationjourney',
            name='current_stage',
            field=models.CharField(choices=[('tension_observer', 'Tension Observer'), ('awareness_lens', 'Awareness Lens'), ('belief_anchor', 'Belief Anchor'), ('thought_analyzer', 'Thought Analyzer'), ('faith_cycle', 'Faith Cycle'), ('clarity_flow', 'Clarity Flow'), ('celebration', 'Celebration')], max_length=50),
        ),
    ]
