# Generated by Django 6.1 on 2026-09-07 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core_healing_path', '0004_remove_healinglog_belief_healinglog_celebration_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healinglog',
            name='celebration_type',
        ),
        migrations.RemoveField(
            model_name='healinglog',
            name='joy_notes',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='current_streak_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_activity_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='streak_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_points',
        ),
        migrations.AddField(
            model_name='healinglog',
            name='awareness_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='healinglog',
            name='parent_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awareness_entries', to='Core_healing_path.healinglog'),
        ),
        migrations.AlterField(
            model_name='healinglog',
            name='stage',
            field=models.CharField(choices=[('tension_observer', 'Tension Observer'), ('awareness_lens', 'Awareness Lens'), ('belief_anchor', 'Belief Anchor'), ('thought_analyzer', 'Thought Analyzer'), ('faith_cycle', 'Faith Cycle'), ('clarity_flow', 'Clarity Flow')], max_length=50),
        ),
        migrations.AlterField(
            model_name='journeystage',
            name='stage',
            field=models.CharField(choices=[('tension_observer', 'Tension Observer'), ('awareness_lens', 'Awareness Lens'), ('belief_anchor', 'Belief Anchor'), ('thought_analyzer', 'Thought Analyzer'), ('faith_cycle', 'Faith Cycle'), ('clarity_flow', 'Clarity Flow')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transformationjourney',
            name='current_stage',
            field=models.CharField(choices=[('tension_observer', 'Tension Observer'), ('awareness_lens', 'Awareness Lens'), ('belief_anchor', 'Belief Anchor'), ('thought_analyzer', 'Thought Analyzer'), ('faith_cycle', 'Faith Cycle'), ('clarity_flow', 'Clarity Flow')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
