# Generated by Django 6.1 on 2026-09-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('facility', models.CharField(blank=True, max_length=200)),
                ('indicators', models.JSONField(default=dict)),
                ('activities', models.TextField(blank=True)),
                ('meetings', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('solutions', models.TextField(blank=True)),
                ('daily_plan', models.TextField(blank=True)),
                ('achievements', models.TextField(blank=True)),
                ('failures', models.TextField(blank=True)),
                ('gains', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
