# Generated by Django 6.1 on 2026-09-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_alignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='indicators_baseline',
            field=models.JSONField(default=dict),
        ),
    ]
