# Generated by Django 6.1 on 2026-09-14 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_alignment', '0002_worklog_indicators_baseline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='failures',
        ),
    ]
